### ISSUE TITLE
Support updating pull request status instead of only commits

### ISSUE THREAD

**Issue by triztian** [mediusoft/bitrise-step-azure-devops-status#1]
As the title states the URL in `step.sh` is hardcoded to a `commits` path. It'd be nice if it would be able to support urls like the following: 

```
https://$devops_user:$devops_pat@dev.azure.com/${devops_organization}/${devops_project}/_apis/git/repositories/${devops_repository_id}/${devops_object_type}/${devops_object_id}/statuses?api-version=5.1
```

The inputs could be updated to the following:

```
- devops_object_type: commit
  opts:
    description: |
      The type of object that is being updated.

      Possible values are `commits`, `pullRequest`
    is_expand: true
    is_required: false
    title: DevOps Object Type
    value_options:
    - commits
    - pullRequest
```
